version: '3.8'

services:
  tg_scheduled_pfp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_scheduled_pfp
    networks:
      - tg_scheduled_pfp

networks:
  tg_scheduled_pfp:
    driver: bridge
