services:
  tg_scheduled_pfp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    container_name: tg_scheduled_pfp
    environment:
      - API_HASH
      - API_ID
    restart: unless-stopped
    network_mode: bridge
